<?php

/*
* @file
* Views Bootstrap Cards module theme functions.
*/
use Drupal\views\ViewExecutable;
use Drupal\Core\Form\FormStateInterface;

\Drupal::moduleHandler()->loadInclude('views_bootstrap_cards', 'inc', 'views_bootstrap_cards.theme');

/*
*Implements hook_theme().
*/
function views_bootstrap_cards_theme($existing, $type, $theme, $path) {
  return array(
    'views_bootstrap_cards' => array(
      'file' => 'views_bootstrap_cards.theme.inc',
    )
  );
}

/*
*Implements views_pre_render
*/
function views_bootstrap_cards_views_pre_render(ViewExecutable $view) {
  $view->element['#attached']['library'][] = 'views_bootstrap_cards/cards';
}
